import React,{useState} from 'react'
import { ActivityIndicator } from 'react-native';
import { OpaqueColorValue } from 'react-native';
import { View,StyleSheet,FlatList,TouchableOpacity } from 'react-native'
import {Icon,Header,Text,Image,StatusBar } from 'react-native-elements';

const ArticleScreen = (props) => {
    const data = [
        {id:1, likes:12, image:"https://images.unsplash.com/photo-1539176170444-67d6c8f356d1?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=670&q=80", title:"How to prune", writer:"Unga Bunga", text: `

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pulvinar dignissim urna, id porttitor tortor eleifend non. Nullam eget viverra risus. Nulla sit amet lacus condimentum, sodales leo faucibus, semper est. Cras ultrices auctor purus eu tempus. Nullam id felis sodales, ultrices nunc a, consequat quam. Cras ac mi eget sem dapibus condimentum congue consectetur neque. Maecenas cursus euismod sodales. Phasellus id condimentum orci. In hac habitasse platea dictumst. Quisque vel posuere libero. Maecenas ac iaculis dolor, ut ultricies arcu. Maecenas convallis justo id quam tempor, vitae mollis purus auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Proin interdum, felis ut elementum cursus, ligula leo sodales diam, eu dapibus odio nulla sed nulla. Nunc diam felis, maximus nec nisl et, semper euismod risus. Suspendisse luctus, massa in interdum viverra, eros arcu vehicula nibh, quis vestibulum est ante suscipit nisi. Quisque sed elit non elit tempor volutpat id eu augue. Donec lacinia enim sed justo aliquet, quis rutrum felis aliquet. Pellentesque sit amet aliquam nisi. Integer in commodo turpis, quis sagittis diam. Nullam faucibus tortor porta augue ultrices semper. Proin dapibus scelerisque sapien, non fermentum erat. Aliquam dignissim non nisi interdum sodales. Cras ut enim sem. Maecenas convallis semper ex, non varius erat. Phasellus bibendum odio vitae dui tempus faucibus. Integer tincidunt, est id auctor tempor, lorem nisl molestie tortor, at interdum arcu mi imperdiet elit. Duis nec tortor a erat mattis fermentum.

Nam in aliquam neque. Curabitur leo nulla, blandit commodo leo id, tristique interdum erat. Cras at erat sed velit dapibus sollicitudin maximus sed tortor. Vivamus fermentum eros a purus efficitur, et eleifend felis fermentum. Nam efficitur mi erat, pulvinar tempor odio tempus vel. Suspendisse eget sagittis ante. Integer ultricies mi tortor. Quisque hendrerit massa scelerisque velit elementum, eget vehicula lacus maximus. Ut tortor leo, auctor eget viverra et, condimentum viverra nibh. Nulla in arcu porttitor, finibus eros vel, consequat augue. Praesent nec porttitor risus. Vivamus tristique, neque vitae feugiat vulputate, justo purus porta nisl, ut commodo dolor nisl ut mauris. Integer pellentesque efficitur laoreet. Quisque pulvinar ultrices quam, in sodales diam pretium eget.

Aenean mi arcu, condimentum et varius at, semper maximus turpis. Maecenas posuere consequat ultricies. Etiam eget lectus est. Praesent vulputate eu massa a ornare. Nam vestibulum, mauris a lacinia eleifend, leo nibh imperdiet ante, ut auctor ex massa id leo. Aenean ornare convallis lectus, nec pharetra mi tincidunt vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. In porttitor neque sed dui varius feugiat. Donec sem quam, lacinia volutpat est ac, aliquet egestas ante. Etiam blandit tempus ex ut ultricies. Aenean laoreet et tortor sed fringilla. Suspendisse potenti. Sed accumsan vitae mi id mattis. Vestibulum vitae mauris eget dui mattis iaculis nec vel est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Praesent interdum eget libero vel feugiat. Ut venenatis ultrices nibh, nec porttitor eros consectetur a. Cras eget lobortis nibh. Ut vitae mauris tempus, semper quam consectetur, iaculis lorem. Aliquam ultricies massa in aliquam auctor. Integer eget molestie ante. Ut ut lacus venenatis, hendrerit velit sed, consequat felis. Aenean et metus ac tortor fringilla tempus. Suspendisse potenti. In quis lobortis purus. Vivamus finibus lobortis sem eu facilisis. Quisque laoreet auctor eros, aliquam pulvinar enim. Curabitur non leo vitae felis gravida euismod non ac magna. Integer faucibus nisi id pellentesque consectetur. `},
        {id:2, likes:11, image:"https://images.unsplash.com/photo-1467043198406-dc953a3defa0?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=670&q=80", title:"How to change soil", writer:"Unga Bunga", text: `

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pulvinar dignissim urna, id porttitor tortor eleifend non. Nullam eget viverra risus. Nulla sit amet lacus condimentum, sodales leo faucibus, semper est. Cras ultrices auctor purus eu tempus. Nullam id felis sodales, ultrices nunc a, consequat quam. Cras ac mi eget sem dapibus condimentum congue consectetur neque. Maecenas cursus euismod sodales. Phasellus id condimentum orci. In hac habitasse platea dictumst. Quisque vel posuere libero. Maecenas ac iaculis dolor, ut ultricies arcu. Maecenas convallis justo id quam tempor, vitae mollis purus auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Proin interdum, felis ut elementum cursus, ligula leo sodales diam, eu dapibus odio nulla sed nulla. Nunc diam felis, maximus nec nisl et, semper euismod risus. Suspendisse luctus, massa in interdum viverra, eros arcu vehicula nibh, quis vestibulum est ante suscipit nisi. Quisque sed elit non elit tempor volutpat id eu augue. Donec lacinia enim sed justo aliquet, quis rutrum felis aliquet. Pellentesque sit amet aliquam nisi. Integer in commodo turpis, quis sagittis diam. Nullam faucibus tortor porta augue ultrices semper. Proin dapibus scelerisque sapien, non fermentum erat. Aliquam dignissim non nisi interdum sodales. Cras ut enim sem. Maecenas convallis semper ex, non varius erat. Phasellus bibendum odio vitae dui tempus faucibus. Integer tincidunt, est id auctor tempor, lorem nisl molestie tortor, at interdum arcu mi imperdiet elit. Duis nec tortor a erat mattis fermentum.

Nam in aliquam neque. Curabitur leo nulla, blandit commodo leo id, tristique interdum erat. Cras at erat sed velit dapibus sollicitudin maximus sed tortor. Vivamus fermentum eros a purus efficitur, et eleifend felis fermentum. Nam efficitur mi erat, pulvinar tempor odio tempus vel. Suspendisse eget sagittis ante. Integer ultricies mi tortor. Quisque hendrerit massa scelerisque velit elementum, eget vehicula lacus maximus. Ut tortor leo, auctor eget viverra et, condimentum viverra nibh. Nulla in arcu porttitor, finibus eros vel, consequat augue. Praesent nec porttitor risus. Vivamus tristique, neque vitae feugiat vulputate, justo purus porta nisl, ut commodo dolor nisl ut mauris. Integer pellentesque efficitur laoreet. Quisque pulvinar ultrices quam, in sodales diam pretium eget.

Aenean mi arcu, condimentum et varius at, semper maximus turpis. Maecenas posuere consequat ultricies. Etiam eget lectus est. Praesent vulputate eu massa a ornare. Nam vestibulum, mauris a lacinia eleifend, leo nibh imperdiet ante, ut auctor ex massa id leo. Aenean ornare convallis lectus, nec pharetra mi tincidunt vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. In porttitor neque sed dui varius feugiat. Donec sem quam, lacinia volutpat est ac, aliquet egestas ante. Etiam blandit tempus ex ut ultricies. Aenean laoreet et tortor sed fringilla. Suspendisse potenti. Sed accumsan vitae mi id mattis. Vestibulum vitae mauris eget dui mattis iaculis nec vel est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Praesent interdum eget libero vel feugiat. Ut venenatis ultrices nibh, nec porttitor eros consectetur a. Cras eget lobortis nibh. Ut vitae mauris tempus, semper quam consectetur, iaculis lorem. Aliquam ultricies massa in aliquam auctor. Integer eget molestie ante. Ut ut lacus venenatis, hendrerit velit sed, consequat felis. Aenean et metus ac tortor fringilla tempus. Suspendisse potenti. In quis lobortis purus. Vivamus finibus lobortis sem eu facilisis. Quisque laoreet auctor eros, aliquam pulvinar enim. Curabitur non leo vitae felis gravida euismod non ac magna. Integer faucibus nisi id pellentesque consectetur. `},
        {id:3, likes:25, image:"https://images.unsplash.com/photo-1526397751294-331021109fbd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1267&q=80", title:"Shaping a junyper", writer:"Unga Bunga", text: `

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pulvinar dignissim urna, id porttitor tortor eleifend non. Nullam eget viverra risus. Nulla sit amet lacus condimentum, sodales leo faucibus, semper est. Cras ultrices auctor purus eu tempus. Nullam id felis sodales, ultrices nunc a, consequat quam. Cras ac mi eget sem dapibus condimentum congue consectetur neque. Maecenas cursus euismod sodales. Phasellus id condimentum orci. In hac habitasse platea dictumst. Quisque vel posuere libero. Maecenas ac iaculis dolor, ut ultricies arcu. Maecenas convallis justo id quam tempor, vitae mollis purus auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Proin interdum, felis ut elementum cursus, ligula leo sodales diam, eu dapibus odio nulla sed nulla. Nunc diam felis, maximus nec nisl et, semper euismod risus. Suspendisse luctus, massa in interdum viverra, eros arcu vehicula nibh, quis vestibulum est ante suscipit nisi. Quisque sed elit non elit tempor volutpat id eu augue. Donec lacinia enim sed justo aliquet, quis rutrum felis aliquet. Pellentesque sit amet aliquam nisi. Integer in commodo turpis, quis sagittis diam. Nullam faucibus tortor porta augue ultrices semper. Proin dapibus scelerisque sapien, non fermentum erat. Aliquam dignissim non nisi interdum sodales. Cras ut enim sem. Maecenas convallis semper ex, non varius erat. Phasellus bibendum odio vitae dui tempus faucibus. Integer tincidunt, est id auctor tempor, lorem nisl molestie tortor, at interdum arcu mi imperdiet elit. Duis nec tortor a erat mattis fermentum.

Nam in aliquam neque. Curabitur leo nulla, blandit commodo leo id, tristique interdum erat. Cras at erat sed velit dapibus sollicitudin maximus sed tortor. Vivamus fermentum eros a purus efficitur, et eleifend felis fermentum. Nam efficitur mi erat, pulvinar tempor odio tempus vel. Suspendisse eget sagittis ante. Integer ultricies mi tortor. Quisque hendrerit massa scelerisque velit elementum, eget vehicula lacus maximus. Ut tortor leo, auctor eget viverra et, condimentum viverra nibh. Nulla in arcu porttitor, finibus eros vel, consequat augue. Praesent nec porttitor risus. Vivamus tristique, neque vitae feugiat vulputate, justo purus porta nisl, ut commodo dolor nisl ut mauris. Integer pellentesque efficitur laoreet. Quisque pulvinar ultrices quam, in sodales diam pretium eget.

Aenean mi arcu, condimentum et varius at, semper maximus turpis. Maecenas posuere consequat ultricies. Etiam eget lectus est. Praesent vulputate eu massa a ornare. Nam vestibulum, mauris a lacinia eleifend, leo nibh imperdiet ante, ut auctor ex massa id leo. Aenean ornare convallis lectus, nec pharetra mi tincidunt vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. In porttitor neque sed dui varius feugiat. Donec sem quam, lacinia volutpat est ac, aliquet egestas ante. Etiam blandit tempus ex ut ultricies. Aenean laoreet et tortor sed fringilla. Suspendisse potenti. Sed accumsan vitae mi id mattis. Vestibulum vitae mauris eget dui mattis iaculis nec vel est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Praesent interdum eget libero vel feugiat. Ut venenatis ultrices nibh, nec porttitor eros consectetur a. Cras eget lobortis nibh. Ut vitae mauris tempus, semper quam consectetur, iaculis lorem. Aliquam ultricies massa in aliquam auctor. Integer eget molestie ante. Ut ut lacus venenatis, hendrerit velit sed, consequat felis. Aenean et metus ac tortor fringilla tempus. Suspendisse potenti. In quis lobortis purus. Vivamus finibus lobortis sem eu facilisis. Quisque laoreet auctor eros, aliquam pulvinar enim. Curabitur non leo vitae felis gravida euismod non ac magna. Integer faucibus nisi id pellentesque consectetur. `}, 
        {id:4, likes:12, image:"https://images.unsplash.com/photo-1569873175476-10aa45523ab8?ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8Ym9uc2FpfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60", title:"Caring maple", writer:"Unga Bunga", text: `

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pulvinar dignissim urna, id porttitor tortor eleifend non. Nullam eget viverra risus. Nulla sit amet lacus condimentum, sodales leo faucibus, semper est. Cras ultrices auctor purus eu tempus. Nullam id felis sodales, ultrices nunc a, consequat quam. Cras ac mi eget sem dapibus condimentum congue consectetur neque. Maecenas cursus euismod sodales. Phasellus id condimentum orci. In hac habitasse platea dictumst. Quisque vel posuere libero. Maecenas ac iaculis dolor, ut ultricies arcu. Maecenas convallis justo id quam tempor, vitae mollis purus auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Proin interdum, felis ut elementum cursus, ligula leo sodales diam, eu dapibus odio nulla sed nulla. Nunc diam felis, maximus nec nisl et, semper euismod risus. Suspendisse luctus, massa in interdum viverra, eros arcu vehicula nibh, quis vestibulum est ante suscipit nisi. Quisque sed elit non elit tempor volutpat id eu augue. Donec lacinia enim sed justo aliquet, quis rutrum felis aliquet. Pellentesque sit amet aliquam nisi. Integer in commodo turpis, quis sagittis diam. Nullam faucibus tortor porta augue ultrices semper. Proin dapibus scelerisque sapien, non fermentum erat. Aliquam dignissim non nisi interdum sodales. Cras ut enim sem. Maecenas convallis semper ex, non varius erat. Phasellus bibendum odio vitae dui tempus faucibus. Integer tincidunt, est id auctor tempor, lorem nisl molestie tortor, at interdum arcu mi imperdiet elit. Duis nec tortor a erat mattis fermentum.

Nam in aliquam neque. Curabitur leo nulla, blandit commodo leo id, tristique interdum erat. Cras at erat sed velit dapibus sollicitudin maximus sed tortor. Vivamus fermentum eros a purus efficitur, et eleifend felis fermentum. Nam efficitur mi erat, pulvinar tempor odio tempus vel. Suspendisse eget sagittis ante. Integer ultricies mi tortor. Quisque hendrerit massa scelerisque velit elementum, eget vehicula lacus maximus. Ut tortor leo, auctor eget viverra et, condimentum viverra nibh. Nulla in arcu porttitor, finibus eros vel, consequat augue. Praesent nec porttitor risus. Vivamus tristique, neque vitae feugiat vulputate, justo purus porta nisl, ut commodo dolor nisl ut mauris. Integer pellentesque efficitur laoreet. Quisque pulvinar ultrices quam, in sodales diam pretium eget.

Aenean mi arcu, condimentum et varius at, semper maximus turpis. Maecenas posuere consequat ultricies. Etiam eget lectus est. Praesent vulputate eu massa a ornare. Nam vestibulum, mauris a lacinia eleifend, leo nibh imperdiet ante, ut auctor ex massa id leo. Aenean ornare convallis lectus, nec pharetra mi tincidunt vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. In porttitor neque sed dui varius feugiat. Donec sem quam, lacinia volutpat est ac, aliquet egestas ante. Etiam blandit tempus ex ut ultricies. Aenean laoreet et tortor sed fringilla. Suspendisse potenti. Sed accumsan vitae mi id mattis. Vestibulum vitae mauris eget dui mattis iaculis nec vel est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Praesent interdum eget libero vel feugiat. Ut venenatis ultrices nibh, nec porttitor eros consectetur a. Cras eget lobortis nibh. Ut vitae mauris tempus, semper quam consectetur, iaculis lorem. Aliquam ultricies massa in aliquam auctor. Integer eget molestie ante. Ut ut lacus venenatis, hendrerit velit sed, consequat felis. Aenean et metus ac tortor fringilla tempus. Suspendisse potenti. In quis lobortis purus. Vivamus finibus lobortis sem eu facilisis. Quisque laoreet auctor eros, aliquam pulvinar enim. Curabitur non leo vitae felis gravida euismod non ac magna. Integer faucibus nisi id pellentesque consectetur. `}, 
        {id:5, likes:10, image:"https://images.unsplash.com/photo-1611387729672-25583e070328?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=675&q=80", title:"A guide to Bonsai Forests", writer:"Unga Bunga", text: `

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pulvinar dignissim urna, id porttitor tortor eleifend non. Nullam eget viverra risus. Nulla sit amet lacus condimentum, sodales leo faucibus, semper est. Cras ultrices auctor purus eu tempus. Nullam id felis sodales, ultrices nunc a, consequat quam. Cras ac mi eget sem dapibus condimentum congue consectetur neque. Maecenas cursus euismod sodales. Phasellus id condimentum orci. In hac habitasse platea dictumst. Quisque vel posuere libero. Maecenas ac iaculis dolor, ut ultricies arcu. Maecenas convallis justo id quam tempor, vitae mollis purus auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Proin interdum, felis ut elementum cursus, ligula leo sodales diam, eu dapibus odio nulla sed nulla. Nunc diam felis, maximus nec nisl et, semper euismod risus. Suspendisse luctus, massa in interdum viverra, eros arcu vehicula nibh, quis vestibulum est ante suscipit nisi. Quisque sed elit non elit tempor volutpat id eu augue. Donec lacinia enim sed justo aliquet, quis rutrum felis aliquet. Pellentesque sit amet aliquam nisi. Integer in commodo turpis, quis sagittis diam. Nullam faucibus tortor porta augue ultrices semper. Proin dapibus scelerisque sapien, non fermentum erat. Aliquam dignissim non nisi interdum sodales. Cras ut enim sem. Maecenas convallis semper ex, non varius erat. Phasellus bibendum odio vitae dui tempus faucibus. Integer tincidunt, est id auctor tempor, lorem nisl molestie tortor, at interdum arcu mi imperdiet elit. Duis nec tortor a erat mattis fermentum.

Nam in aliquam neque. Curabitur leo nulla, blandit commodo leo id, tristique interdum erat. Cras at erat sed velit dapibus sollicitudin maximus sed tortor. Vivamus fermentum eros a purus efficitur, et eleifend felis fermentum. Nam efficitur mi erat, pulvinar tempor odio tempus vel. Suspendisse eget sagittis ante. Integer ultricies mi tortor. Quisque hendrerit massa scelerisque velit elementum, eget vehicula lacus maximus. Ut tortor leo, auctor eget viverra et, condimentum viverra nibh. Nulla in arcu porttitor, finibus eros vel, consequat augue. Praesent nec porttitor risus. Vivamus tristique, neque vitae feugiat vulputate, justo purus porta nisl, ut commodo dolor nisl ut mauris. Integer pellentesque efficitur laoreet. Quisque pulvinar ultrices quam, in sodales diam pretium eget.

Aenean mi arcu, condimentum et varius at, semper maximus turpis. Maecenas posuere consequat ultricies. Etiam eget lectus est. Praesent vulputate eu massa a ornare. Nam vestibulum, mauris a lacinia eleifend, leo nibh imperdiet ante, ut auctor ex massa id leo. Aenean ornare convallis lectus, nec pharetra mi tincidunt vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. In porttitor neque sed dui varius feugiat. Donec sem quam, lacinia volutpat est ac, aliquet egestas ante. Etiam blandit tempus ex ut ultricies. Aenean laoreet et tortor sed fringilla. Suspendisse potenti. Sed accumsan vitae mi id mattis. Vestibulum vitae mauris eget dui mattis iaculis nec vel est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Praesent interdum eget libero vel feugiat. Ut venenatis ultrices nibh, nec porttitor eros consectetur a. Cras eget lobortis nibh. Ut vitae mauris tempus, semper quam consectetur, iaculis lorem. Aliquam ultricies massa in aliquam auctor. Integer eget molestie ante. Ut ut lacus venenatis, hendrerit velit sed, consequat felis. Aenean et metus ac tortor fringilla tempus. Suspendisse potenti. In quis lobortis purus. Vivamus finibus lobortis sem eu facilisis. Quisque laoreet auctor eros, aliquam pulvinar enim. Curabitur non leo vitae felis gravida euismod non ac magna. Integer faucibus nisi id pellentesque consectetur. `}, 
        {id:6, likes:12, image:"https://images.unsplash.com/photo-1613143323550-7a9044756070?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=675&q=80", title:"Selecting right pot", writer:"Unga Bunga", text: `

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pulvinar dignissim urna, id porttitor tortor eleifend non. Nullam eget viverra risus. Nulla sit amet lacus condimentum, sodales leo faucibus, semper est. Cras ultrices auctor purus eu tempus. Nullam id felis sodales, ultrices nunc a, consequat quam. Cras ac mi eget sem dapibus condimentum congue consectetur neque. Maecenas cursus euismod sodales. Phasellus id condimentum orci. In hac habitasse platea dictumst. Quisque vel posuere libero. Maecenas ac iaculis dolor, ut ultricies arcu. Maecenas convallis justo id quam tempor, vitae mollis purus auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Proin interdum, felis ut elementum cursus, ligula leo sodales diam, eu dapibus odio nulla sed nulla. Nunc diam felis, maximus nec nisl et, semper euismod risus. Suspendisse luctus, massa in interdum viverra, eros arcu vehicula nibh, quis vestibulum est ante suscipit nisi. Quisque sed elit non elit tempor volutpat id eu augue. Donec lacinia enim sed justo aliquet, quis rutrum felis aliquet. Pellentesque sit amet aliquam nisi. Integer in commodo turpis, quis sagittis diam. Nullam faucibus tortor porta augue ultrices semper. Proin dapibus scelerisque sapien, non fermentum erat. Aliquam dignissim non nisi interdum sodales. Cras ut enim sem. Maecenas convallis semper ex, non varius erat. Phasellus bibendum odio vitae dui tempus faucibus. Integer tincidunt, est id auctor tempor, lorem nisl molestie tortor, at interdum arcu mi imperdiet elit. Duis nec tortor a erat mattis fermentum.

Nam in aliquam neque. Curabitur leo nulla, blandit commodo leo id, tristique interdum erat. Cras at erat sed velit dapibus sollicitudin maximus sed tortor. Vivamus fermentum eros a purus efficitur, et eleifend felis fermentum. Nam efficitur mi erat, pulvinar tempor odio tempus vel. Suspendisse eget sagittis ante. Integer ultricies mi tortor. Quisque hendrerit massa scelerisque velit elementum, eget vehicula lacus maximus. Ut tortor leo, auctor eget viverra et, condimentum viverra nibh. Nulla in arcu porttitor, finibus eros vel, consequat augue. Praesent nec porttitor risus. Vivamus tristique, neque vitae feugiat vulputate, justo purus porta nisl, ut commodo dolor nisl ut mauris. Integer pellentesque efficitur laoreet. Quisque pulvinar ultrices quam, in sodales diam pretium eget.

Aenean mi arcu, condimentum et varius at, semper maximus turpis. Maecenas posuere consequat ultricies. Etiam eget lectus est. Praesent vulputate eu massa a ornare. Nam vestibulum, mauris a lacinia eleifend, leo nibh imperdiet ante, ut auctor ex massa id leo. Aenean ornare convallis lectus, nec pharetra mi tincidunt vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. In porttitor neque sed dui varius feugiat. Donec sem quam, lacinia volutpat est ac, aliquet egestas ante. Etiam blandit tempus ex ut ultricies. Aenean laoreet et tortor sed fringilla. Suspendisse potenti. Sed accumsan vitae mi id mattis. Vestibulum vitae mauris eget dui mattis iaculis nec vel est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Praesent interdum eget libero vel feugiat. Ut venenatis ultrices nibh, nec porttitor eros consectetur a. Cras eget lobortis nibh. Ut vitae mauris tempus, semper quam consectetur, iaculis lorem. Aliquam ultricies massa in aliquam auctor. Integer eget molestie ante. Ut ut lacus venenatis, hendrerit velit sed, consequat felis. Aenean et metus ac tortor fringilla tempus. Suspendisse potenti. In quis lobortis purus. Vivamus finibus lobortis sem eu facilisis. Quisque laoreet auctor eros, aliquam pulvinar enim. Curabitur non leo vitae felis gravida euismod non ac magna. Integer faucibus nisi id pellentesque consectetur. `}, 
        {id:7, likes:34, image:"https://images.unsplash.com/photo-1586170112425-3adf1ed0146e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80", title:"All about Hibiscus", writer:"Unga Bunga", text: `

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pulvinar dignissim urna, id porttitor tortor eleifend non. Nullam eget viverra risus. Nulla sit amet lacus condimentum, sodales leo faucibus, semper est. Cras ultrices auctor purus eu tempus. Nullam id felis sodales, ultrices nunc a, consequat quam. Cras ac mi eget sem dapibus condimentum congue consectetur neque. Maecenas cursus euismod sodales. Phasellus id condimentum orci. In hac habitasse platea dictumst. Quisque vel posuere libero. Maecenas ac iaculis dolor, ut ultricies arcu. Maecenas convallis justo id quam tempor, vitae mollis purus auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Proin interdum, felis ut elementum cursus, ligula leo sodales diam, eu dapibus odio nulla sed nulla. Nunc diam felis, maximus nec nisl et, semper euismod risus. Suspendisse luctus, massa in interdum viverra, eros arcu vehicula nibh, quis vestibulum est ante suscipit nisi. Quisque sed elit non elit tempor volutpat id eu augue. Donec lacinia enim sed justo aliquet, quis rutrum felis aliquet. Pellentesque sit amet aliquam nisi. Integer in commodo turpis, quis sagittis diam. Nullam faucibus tortor porta augue ultrices semper. Proin dapibus scelerisque sapien, non fermentum erat. Aliquam dignissim non nisi interdum sodales. Cras ut enim sem. Maecenas convallis semper ex, non varius erat. Phasellus bibendum odio vitae dui tempus faucibus. Integer tincidunt, est id auctor tempor, lorem nisl molestie tortor, at interdum arcu mi imperdiet elit. Duis nec tortor a erat mattis fermentum.

Nam in aliquam neque. Curabitur leo nulla, blandit commodo leo id, tristique interdum erat. Cras at erat sed velit dapibus sollicitudin maximus sed tortor. Vivamus fermentum eros a purus efficitur, et eleifend felis fermentum. Nam efficitur mi erat, pulvinar tempor odio tempus vel. Suspendisse eget sagittis ante. Integer ultricies mi tortor. Quisque hendrerit massa scelerisque velit elementum, eget vehicula lacus maximus. Ut tortor leo, auctor eget viverra et, condimentum viverra nibh. Nulla in arcu porttitor, finibus eros vel, consequat augue. Praesent nec porttitor risus. Vivamus tristique, neque vitae feugiat vulputate, justo purus porta nisl, ut commodo dolor nisl ut mauris. Integer pellentesque efficitur laoreet. Quisque pulvinar ultrices quam, in sodales diam pretium eget.

Aenean mi arcu, condimentum et varius at, semper maximus turpis. Maecenas posuere consequat ultricies. Etiam eget lectus est. Praesent vulputate eu massa a ornare. Nam vestibulum, mauris a lacinia eleifend, leo nibh imperdiet ante, ut auctor ex massa id leo. Aenean ornare convallis lectus, nec pharetra mi tincidunt vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. In porttitor neque sed dui varius feugiat. Donec sem quam, lacinia volutpat est ac, aliquet egestas ante. Etiam blandit tempus ex ut ultricies. Aenean laoreet et tortor sed fringilla. Suspendisse potenti. Sed accumsan vitae mi id mattis. Vestibulum vitae mauris eget dui mattis iaculis nec vel est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Praesent interdum eget libero vel feugiat. Ut venenatis ultrices nibh, nec porttitor eros consectetur a. Cras eget lobortis nibh. Ut vitae mauris tempus, semper quam consectetur, iaculis lorem. Aliquam ultricies massa in aliquam auctor. Integer eget molestie ante. Ut ut lacus venenatis, hendrerit velit sed, consequat felis. Aenean et metus ac tortor fringilla tempus. Suspendisse potenti. In quis lobortis purus. Vivamus finibus lobortis sem eu facilisis. Quisque laoreet auctor eros, aliquam pulvinar enim. Curabitur non leo vitae felis gravida euismod non ac magna. Integer faucibus nisi id pellentesque consectetur. `}, 
        {id:8, likes:45, image:"https://images.unsplash.com/photo-1470364693235-a4fe27c60914?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=634&q=80", title:"Tools Manual", writer:"Unga Bunga", text: `

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pulvinar dignissim urna, id porttitor tortor eleifend non. Nullam eget viverra risus. Nulla sit amet lacus condimentum, sodales leo faucibus, semper est. Cras ultrices auctor purus eu tempus. Nullam id felis sodales, ultrices nunc a, consequat quam. Cras ac mi eget sem dapibus condimentum congue consectetur neque. Maecenas cursus euismod sodales. Phasellus id condimentum orci. In hac habitasse platea dictumst. Quisque vel posuere libero. Maecenas ac iaculis dolor, ut ultricies arcu. Maecenas convallis justo id quam tempor, vitae mollis purus auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Proin interdum, felis ut elementum cursus, ligula leo sodales diam, eu dapibus odio nulla sed nulla. Nunc diam felis, maximus nec nisl et, semper euismod risus. Suspendisse luctus, massa in interdum viverra, eros arcu vehicula nibh, quis vestibulum est ante suscipit nisi. Quisque sed elit non elit tempor volutpat id eu augue. Donec lacinia enim sed justo aliquet, quis rutrum felis aliquet. Pellentesque sit amet aliquam nisi. Integer in commodo turpis, quis sagittis diam. Nullam faucibus tortor porta augue ultrices semper. Proin dapibus scelerisque sapien, non fermentum erat. Aliquam dignissim non nisi interdum sodales. Cras ut enim sem. Maecenas convallis semper ex, non varius erat. Phasellus bibendum odio vitae dui tempus faucibus. Integer tincidunt, est id auctor tempor, lorem nisl molestie tortor, at interdum arcu mi imperdiet elit. Duis nec tortor a erat mattis fermentum.

Nam in aliquam neque. Curabitur leo nulla, blandit commodo leo id, tristique interdum erat. Cras at erat sed velit dapibus sollicitudin maximus sed tortor. Vivamus fermentum eros a purus efficitur, et eleifend felis fermentum. Nam efficitur mi erat, pulvinar tempor odio tempus vel. Suspendisse eget sagittis ante. Integer ultricies mi tortor. Quisque hendrerit massa scelerisque velit elementum, eget vehicula lacus maximus. Ut tortor leo, auctor eget viverra et, condimentum viverra nibh. Nulla in arcu porttitor, finibus eros vel, consequat augue. Praesent nec porttitor risus. Vivamus tristique, neque vitae feugiat vulputate, justo purus porta nisl, ut commodo dolor nisl ut mauris. Integer pellentesque efficitur laoreet. Quisque pulvinar ultrices quam, in sodales diam pretium eget.

Aenean mi arcu, condimentum et varius at, semper maximus turpis. Maecenas posuere consequat ultricies. Etiam eget lectus est. Praesent vulputate eu massa a ornare. Nam vestibulum, mauris a lacinia eleifend, leo nibh imperdiet ante, ut auctor ex massa id leo. Aenean ornare convallis lectus, nec pharetra mi tincidunt vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. In porttitor neque sed dui varius feugiat. Donec sem quam, lacinia volutpat est ac, aliquet egestas ante. Etiam blandit tempus ex ut ultricies. Aenean laoreet et tortor sed fringilla. Suspendisse potenti. Sed accumsan vitae mi id mattis. Vestibulum vitae mauris eget dui mattis iaculis nec vel est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Praesent interdum eget libero vel feugiat. Ut venenatis ultrices nibh, nec porttitor eros consectetur a. Cras eget lobortis nibh. Ut vitae mauris tempus, semper quam consectetur, iaculis lorem. Aliquam ultricies massa in aliquam auctor. Integer eget molestie ante. Ut ut lacus venenatis, hendrerit velit sed, consequat felis. Aenean et metus ac tortor fringilla tempus. Suspendisse potenti. In quis lobortis purus. Vivamus finibus lobortis sem eu facilisis. Quisque laoreet auctor eros, aliquam pulvinar enim. Curabitur non leo vitae felis gravida euismod non ac magna. Integer faucibus nisi id pellentesque consectetur. `},
        {id:9, likes:32, image:"https://images.unsplash.com/photo-1569677229133-730f610ae381?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=635&q=80", title:"All about citrus", writer:"Unga Bunga", text: `

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pulvinar dignissim urna, id porttitor tortor eleifend non. Nullam eget viverra risus. Nulla sit amet lacus condimentum, sodales leo faucibus, semper est. Cras ultrices auctor purus eu tempus. Nullam id felis sodales, ultrices nunc a, consequat quam. Cras ac mi eget sem dapibus condimentum congue consectetur neque. Maecenas cursus euismod sodales. Phasellus id condimentum orci. In hac habitasse platea dictumst. Quisque vel posuere libero. Maecenas ac iaculis dolor, ut ultricies arcu. Maecenas convallis justo id quam tempor, vitae mollis purus auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Proin interdum, felis ut elementum cursus, ligula leo sodales diam, eu dapibus odio nulla sed nulla. Nunc diam felis, maximus nec nisl et, semper euismod risus. Suspendisse luctus, massa in interdum viverra, eros arcu vehicula nibh, quis vestibulum est ante suscipit nisi. Quisque sed elit non elit tempor volutpat id eu augue. Donec lacinia enim sed justo aliquet, quis rutrum felis aliquet. Pellentesque sit amet aliquam nisi. Integer in commodo turpis, quis sagittis diam. Nullam faucibus tortor porta augue ultrices semper. Proin dapibus scelerisque sapien, non fermentum erat. Aliquam dignissim non nisi interdum sodales. Cras ut enim sem. Maecenas convallis semper ex, non varius erat. Phasellus bibendum odio vitae dui tempus faucibus. Integer tincidunt, est id auctor tempor, lorem nisl molestie tortor, at interdum arcu mi imperdiet elit. Duis nec tortor a erat mattis fermentum.

Nam in aliquam neque. Curabitur leo nulla, blandit commodo leo id, tristique interdum erat. Cras at erat sed velit dapibus sollicitudin maximus sed tortor. Vivamus fermentum eros a purus efficitur, et eleifend felis fermentum. Nam efficitur mi erat, pulvinar tempor odio tempus vel. Suspendisse eget sagittis ante. Integer ultricies mi tortor. Quisque hendrerit massa scelerisque velit elementum, eget vehicula lacus maximus. Ut tortor leo, auctor eget viverra et, condimentum viverra nibh. Nulla in arcu porttitor, finibus eros vel, consequat augue. Praesent nec porttitor risus. Vivamus tristique, neque vitae feugiat vulputate, justo purus porta nisl, ut commodo dolor nisl ut mauris. Integer pellentesque efficitur laoreet. Quisque pulvinar ultrices quam, in sodales diam pretium eget.

Aenean mi arcu, condimentum et varius at, semper maximus turpis. Maecenas posuere consequat ultricies. Etiam eget lectus est. Praesent vulputate eu massa a ornare. Nam vestibulum, mauris a lacinia eleifend, leo nibh imperdiet ante, ut auctor ex massa id leo. Aenean ornare convallis lectus, nec pharetra mi tincidunt vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. In porttitor neque sed dui varius feugiat. Donec sem quam, lacinia volutpat est ac, aliquet egestas ante. Etiam blandit tempus ex ut ultricies. Aenean laoreet et tortor sed fringilla. Suspendisse potenti. Sed accumsan vitae mi id mattis. Vestibulum vitae mauris eget dui mattis iaculis nec vel est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Praesent interdum eget libero vel feugiat. Ut venenatis ultrices nibh, nec porttitor eros consectetur a. Cras eget lobortis nibh. Ut vitae mauris tempus, semper quam consectetur, iaculis lorem. Aliquam ultricies massa in aliquam auctor. Integer eget molestie ante. Ut ut lacus venenatis, hendrerit velit sed, consequat felis. Aenean et metus ac tortor fringilla tempus. Suspendisse potenti. In quis lobortis purus. Vivamus finibus lobortis sem eu facilisis. Quisque laoreet auctor eros, aliquam pulvinar enim. Curabitur non leo vitae felis gravida euismod non ac magna. Integer faucibus nisi id pellentesque consectetur. `},
        {id:10, likes:56, image:"https://images.unsplash.com/photo-1511971532930-9d589f9e3a82?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1348&q=80", title:"Creating Hokidachi", writer:"Unga Bunga", text: `

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pulvinar dignissim urna, id porttitor tortor eleifend non. Nullam eget viverra risus. Nulla sit amet lacus condimentum, sodales leo faucibus, semper est. Cras ultrices auctor purus eu tempus. Nullam id felis sodales, ultrices nunc a, consequat quam. Cras ac mi eget sem dapibus condimentum congue consectetur neque. Maecenas cursus euismod sodales. Phasellus id condimentum orci. In hac habitasse platea dictumst. Quisque vel posuere libero. Maecenas ac iaculis dolor, ut ultricies arcu. Maecenas convallis justo id quam tempor, vitae mollis purus auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Proin interdum, felis ut elementum cursus, ligula leo sodales diam, eu dapibus odio nulla sed nulla. Nunc diam felis, maximus nec nisl et, semper euismod risus. Suspendisse luctus, massa in interdum viverra, eros arcu vehicula nibh, quis vestibulum est ante suscipit nisi. Quisque sed elit non elit tempor volutpat id eu augue. Donec lacinia enim sed justo aliquet, quis rutrum felis aliquet. Pellentesque sit amet aliquam nisi. Integer in commodo turpis, quis sagittis diam. Nullam faucibus tortor porta augue ultrices semper. Proin dapibus scelerisque sapien, non fermentum erat. Aliquam dignissim non nisi interdum sodales. Cras ut enim sem. Maecenas convallis semper ex, non varius erat. Phasellus bibendum odio vitae dui tempus faucibus. Integer tincidunt, est id auctor tempor, lorem nisl molestie tortor, at interdum arcu mi imperdiet elit. Duis nec tortor a erat mattis fermentum.

Nam in aliquam neque. Curabitur leo nulla, blandit commodo leo id, tristique interdum erat. Cras at erat sed velit dapibus sollicitudin maximus sed tortor. Vivamus fermentum eros a purus efficitur, et eleifend felis fermentum. Nam efficitur mi erat, pulvinar tempor odio tempus vel. Suspendisse eget sagittis ante. Integer ultricies mi tortor. Quisque hendrerit massa scelerisque velit elementum, eget vehicula lacus maximus. Ut tortor leo, auctor eget viverra et, condimentum viverra nibh. Nulla in arcu porttitor, finibus eros vel, consequat augue. Praesent nec porttitor risus. Vivamus tristique, neque vitae feugiat vulputate, justo purus porta nisl, ut commodo dolor nisl ut mauris. Integer pellentesque efficitur laoreet. Quisque pulvinar ultrices quam, in sodales diam pretium eget.

Aenean mi arcu, condimentum et varius at, semper maximus turpis. Maecenas posuere consequat ultricies. Etiam eget lectus est. Praesent vulputate eu massa a ornare. Nam vestibulum, mauris a lacinia eleifend, leo nibh imperdiet ante, ut auctor ex massa id leo. Aenean ornare convallis lectus, nec pharetra mi tincidunt vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. In porttitor neque sed dui varius feugiat. Donec sem quam, lacinia volutpat est ac, aliquet egestas ante. Etiam blandit tempus ex ut ultricies. Aenean laoreet et tortor sed fringilla. Suspendisse potenti. Sed accumsan vitae mi id mattis. Vestibulum vitae mauris eget dui mattis iaculis nec vel est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Praesent interdum eget libero vel feugiat. Ut venenatis ultrices nibh, nec porttitor eros consectetur a. Cras eget lobortis nibh. Ut vitae mauris tempus, semper quam consectetur, iaculis lorem. Aliquam ultricies massa in aliquam auctor. Integer eget molestie ante. Ut ut lacus venenatis, hendrerit velit sed, consequat felis. Aenean et metus ac tortor fringilla tempus. Suspendisse potenti. In quis lobortis purus. Vivamus finibus lobortis sem eu facilisis. Quisque laoreet auctor eros, aliquam pulvinar enim. Curabitur non leo vitae felis gravida euismod non ac magna. Integer faucibus nisi id pellentesque consectetur. `},
        {id:11, likes:12, image:"https://images.unsplash.com/photo-1599598425947-5202edd56bdb?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80", title:"shaping a Windswept", writer:"Unga Bunga", text: `

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pulvinar dignissim urna, id porttitor tortor eleifend non. Nullam eget viverra risus. Nulla sit amet lacus condimentum, sodales leo faucibus, semper est. Cras ultrices auctor purus eu tempus. Nullam id felis sodales, ultrices nunc a, consequat quam. Cras ac mi eget sem dapibus condimentum congue consectetur neque. Maecenas cursus euismod sodales. Phasellus id condimentum orci. In hac habitasse platea dictumst. Quisque vel posuere libero. Maecenas ac iaculis dolor, ut ultricies arcu. Maecenas convallis justo id quam tempor, vitae mollis purus auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Proin interdum, felis ut elementum cursus, ligula leo sodales diam, eu dapibus odio nulla sed nulla. Nunc diam felis, maximus nec nisl et, semper euismod risus. Suspendisse luctus, massa in interdum viverra, eros arcu vehicula nibh, quis vestibulum est ante suscipit nisi. Quisque sed elit non elit tempor volutpat id eu augue. Donec lacinia enim sed justo aliquet, quis rutrum felis aliquet. Pellentesque sit amet aliquam nisi. Integer in commodo turpis, quis sagittis diam. Nullam faucibus tortor porta augue ultrices semper. Proin dapibus scelerisque sapien, non fermentum erat. Aliquam dignissim non nisi interdum sodales. Cras ut enim sem. Maecenas convallis semper ex, non varius erat. Phasellus bibendum odio vitae dui tempus faucibus. Integer tincidunt, est id auctor tempor, lorem nisl molestie tortor, at interdum arcu mi imperdiet elit. Duis nec tortor a erat mattis fermentum.

Nam in aliquam neque. Curabitur leo nulla, blandit commodo leo id, tristique interdum erat. Cras at erat sed velit dapibus sollicitudin maximus sed tortor. Vivamus fermentum eros a purus efficitur, et eleifend felis fermentum. Nam efficitur mi erat, pulvinar tempor odio tempus vel. Suspendisse eget sagittis ante. Integer ultricies mi tortor. Quisque hendrerit massa scelerisque velit elementum, eget vehicula lacus maximus. Ut tortor leo, auctor eget viverra et, condimentum viverra nibh. Nulla in arcu porttitor, finibus eros vel, consequat augue. Praesent nec porttitor risus. Vivamus tristique, neque vitae feugiat vulputate, justo purus porta nisl, ut commodo dolor nisl ut mauris. Integer pellentesque efficitur laoreet. Quisque pulvinar ultrices quam, in sodales diam pretium eget.

Aenean mi arcu, condimentum et varius at, semper maximus turpis. Maecenas posuere consequat ultricies. Etiam eget lectus est. Praesent vulputate eu massa a ornare. Nam vestibulum, mauris a lacinia eleifend, leo nibh imperdiet ante, ut auctor ex massa id leo. Aenean ornare convallis lectus, nec pharetra mi tincidunt vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. In porttitor neque sed dui varius feugiat. Donec sem quam, lacinia volutpat est ac, aliquet egestas ante. Etiam blandit tempus ex ut ultricies. Aenean laoreet et tortor sed fringilla. Suspendisse potenti. Sed accumsan vitae mi id mattis. Vestibulum vitae mauris eget dui mattis iaculis nec vel est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Praesent interdum eget libero vel feugiat. Ut venenatis ultrices nibh, nec porttitor eros consectetur a. Cras eget lobortis nibh. Ut vitae mauris tempus, semper quam consectetur, iaculis lorem. Aliquam ultricies massa in aliquam auctor. Integer eget molestie ante. Ut ut lacus venenatis, hendrerit velit sed, consequat felis. Aenean et metus ac tortor fringilla tempus. Suspendisse potenti. In quis lobortis purus. Vivamus finibus lobortis sem eu facilisis. Quisque laoreet auctor eros, aliquam pulvinar enim. Curabitur non leo vitae felis gravida euismod non ac magna. Integer faucibus nisi id pellentesque consectetur. `}, 
        {id:12, likes:34, image:"https://images.unsplash.com/photo-1605552680957-7862f7265954?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=634&q=80", title:"Creating a Double trunk", writer:"Unga Bunga", text: `

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pulvinar dignissim urna, id porttitor tortor eleifend non. Nullam eget viverra risus. Nulla sit amet lacus condimentum, sodales leo faucibus, semper est. Cras ultrices auctor purus eu tempus. Nullam id felis sodales, ultrices nunc a, consequat quam. Cras ac mi eget sem dapibus condimentum congue consectetur neque. Maecenas cursus euismod sodales. Phasellus id condimentum orci. In hac habitasse platea dictumst. Quisque vel posuere libero. Maecenas ac iaculis dolor, ut ultricies arcu. Maecenas convallis justo id quam tempor, vitae mollis purus auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Proin interdum, felis ut elementum cursus, ligula leo sodales diam, eu dapibus odio nulla sed nulla. Nunc diam felis, maximus nec nisl et, semper euismod risus. Suspendisse luctus, massa in interdum viverra, eros arcu vehicula nibh, quis vestibulum est ante suscipit nisi. Quisque sed elit non elit tempor volutpat id eu augue. Donec lacinia enim sed justo aliquet, quis rutrum felis aliquet. Pellentesque sit amet aliquam nisi. Integer in commodo turpis, quis sagittis diam. Nullam faucibus tortor porta augue ultrices semper. Proin dapibus scelerisque sapien, non fermentum erat. Aliquam dignissim non nisi interdum sodales. Cras ut enim sem. Maecenas convallis semper ex, non varius erat. Phasellus bibendum odio vitae dui tempus faucibus. Integer tincidunt, est id auctor tempor, lorem nisl molestie tortor, at interdum arcu mi imperdiet elit. Duis nec tortor a erat mattis fermentum.

Nam in aliquam neque. Curabitur leo nulla, blandit commodo leo id, tristique interdum erat. Cras at erat sed velit dapibus sollicitudin maximus sed tortor. Vivamus fermentum eros a purus efficitur, et eleifend felis fermentum. Nam efficitur mi erat, pulvinar tempor odio tempus vel. Suspendisse eget sagittis ante. Integer ultricies mi tortor. Quisque hendrerit massa scelerisque velit elementum, eget vehicula lacus maximus. Ut tortor leo, auctor eget viverra et, condimentum viverra nibh. Nulla in arcu porttitor, finibus eros vel, consequat augue. Praesent nec porttitor risus. Vivamus tristique, neque vitae feugiat vulputate, justo purus porta nisl, ut commodo dolor nisl ut mauris. Integer pellentesque efficitur laoreet. Quisque pulvinar ultrices quam, in sodales diam pretium eget.

Aenean mi arcu, condimentum et varius at, semper maximus turpis. Maecenas posuere consequat ultricies. Etiam eget lectus est. Praesent vulputate eu massa a ornare. Nam vestibulum, mauris a lacinia eleifend, leo nibh imperdiet ante, ut auctor ex massa id leo. Aenean ornare convallis lectus, nec pharetra mi tincidunt vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. In porttitor neque sed dui varius feugiat. Donec sem quam, lacinia volutpat est ac, aliquet egestas ante. Etiam blandit tempus ex ut ultricies. Aenean laoreet et tortor sed fringilla. Suspendisse potenti. Sed accumsan vitae mi id mattis. Vestibulum vitae mauris eget dui mattis iaculis nec vel est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Praesent interdum eget libero vel feugiat. Ut venenatis ultrices nibh, nec porttitor eros consectetur a. Cras eget lobortis nibh. Ut vitae mauris tempus, semper quam consectetur, iaculis lorem. Aliquam ultricies massa in aliquam auctor. Integer eget molestie ante. Ut ut lacus venenatis, hendrerit velit sed, consequat felis. Aenean et metus ac tortor fringilla tempus. Suspendisse potenti. In quis lobortis purus. Vivamus finibus lobortis sem eu facilisis. Quisque laoreet auctor eros, aliquam pulvinar enim. Curabitur non leo vitae felis gravida euismod non ac magna. Integer faucibus nisi id pellentesque consectetur. `}, 
        {id:13, likes:45, image:"https://images.unsplash.com/photo-1579450841234-49351e3a312b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=675&q=80", title:"Guide to grow Bonsai on rock", writer:"Unga Bunga", text: `

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pulvinar dignissim urna, id porttitor tortor eleifend non. Nullam eget viverra risus. Nulla sit amet lacus condimentum, sodales leo faucibus, semper est. Cras ultrices auctor purus eu tempus. Nullam id felis sodales, ultrices nunc a, consequat quam. Cras ac mi eget sem dapibus condimentum congue consectetur neque. Maecenas cursus euismod sodales. Phasellus id condimentum orci. In hac habitasse platea dictumst. Quisque vel posuere libero. Maecenas ac iaculis dolor, ut ultricies arcu. Maecenas convallis justo id quam tempor, vitae mollis purus auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Proin interdum, felis ut elementum cursus, ligula leo sodales diam, eu dapibus odio nulla sed nulla. Nunc diam felis, maximus nec nisl et, semper euismod risus. Suspendisse luctus, massa in interdum viverra, eros arcu vehicula nibh, quis vestibulum est ante suscipit nisi. Quisque sed elit non elit tempor volutpat id eu augue. Donec lacinia enim sed justo aliquet, quis rutrum felis aliquet. Pellentesque sit amet aliquam nisi. Integer in commodo turpis, quis sagittis diam. Nullam faucibus tortor porta augue ultrices semper. Proin dapibus scelerisque sapien, non fermentum erat. Aliquam dignissim non nisi interdum sodales. Cras ut enim sem. Maecenas convallis semper ex, non varius erat. Phasellus bibendum odio vitae dui tempus faucibus. Integer tincidunt, est id auctor tempor, lorem nisl molestie tortor, at interdum arcu mi imperdiet elit. Duis nec tortor a erat mattis fermentum.

Nam in aliquam neque. Curabitur leo nulla, blandit commodo leo id, tristique interdum erat. Cras at erat sed velit dapibus sollicitudin maximus sed tortor. Vivamus fermentum eros a purus efficitur, et eleifend felis fermentum. Nam efficitur mi erat, pulvinar tempor odio tempus vel. Suspendisse eget sagittis ante. Integer ultricies mi tortor. Quisque hendrerit massa scelerisque velit elementum, eget vehicula lacus maximus. Ut tortor leo, auctor eget viverra et, condimentum viverra nibh. Nulla in arcu porttitor, finibus eros vel, consequat augue. Praesent nec porttitor risus. Vivamus tristique, neque vitae feugiat vulputate, justo purus porta nisl, ut commodo dolor nisl ut mauris. Integer pellentesque efficitur laoreet. Quisque pulvinar ultrices quam, in sodales diam pretium eget.

Aenean mi arcu, condimentum et varius at, semper maximus turpis. Maecenas posuere consequat ultricies. Etiam eget lectus est. Praesent vulputate eu massa a ornare. Nam vestibulum, mauris a lacinia eleifend, leo nibh imperdiet ante, ut auctor ex massa id leo. Aenean ornare convallis lectus, nec pharetra mi tincidunt vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. In porttitor neque sed dui varius feugiat. Donec sem quam, lacinia volutpat est ac, aliquet egestas ante. Etiam blandit tempus ex ut ultricies. Aenean laoreet et tortor sed fringilla. Suspendisse potenti. Sed accumsan vitae mi id mattis. Vestibulum vitae mauris eget dui mattis iaculis nec vel est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Praesent interdum eget libero vel feugiat. Ut venenatis ultrices nibh, nec porttitor eros consectetur a. Cras eget lobortis nibh. Ut vitae mauris tempus, semper quam consectetur, iaculis lorem. Aliquam ultricies massa in aliquam auctor. Integer eget molestie ante. Ut ut lacus venenatis, hendrerit velit sed, consequat felis. Aenean et metus ac tortor fringilla tempus. Suspendisse potenti. In quis lobortis purus. Vivamus finibus lobortis sem eu facilisis. Quisque laoreet auctor eros, aliquam pulvinar enim. Curabitur non leo vitae felis gravida euismod non ac magna. Integer faucibus nisi id pellentesque consectetur. `},
        {id:14, likes:32, image:"https://images.unsplash.com/photo-1573689705342-73173e359155?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=634&q=80", title:"Shari, Everything you should know", writer:"Unga Bunga", text: `

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pulvinar dignissim urna, id porttitor tortor eleifend non. Nullam eget viverra risus. Nulla sit amet lacus condimentum, sodales leo faucibus, semper est. Cras ultrices auctor purus eu tempus. Nullam id felis sodales, ultrices nunc a, consequat quam. Cras ac mi eget sem dapibus condimentum congue consectetur neque. Maecenas cursus euismod sodales. Phasellus id condimentum orci. In hac habitasse platea dictumst. Quisque vel posuere libero. Maecenas ac iaculis dolor, ut ultricies arcu. Maecenas convallis justo id quam tempor, vitae mollis purus auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Proin interdum, felis ut elementum cursus, ligula leo sodales diam, eu dapibus odio nulla sed nulla. Nunc diam felis, maximus nec nisl et, semper euismod risus. Suspendisse luctus, massa in interdum viverra, eros arcu vehicula nibh, quis vestibulum est ante suscipit nisi. Quisque sed elit non elit tempor volutpat id eu augue. Donec lacinia enim sed justo aliquet, quis rutrum felis aliquet. Pellentesque sit amet aliquam nisi. Integer in commodo turpis, quis sagittis diam. Nullam faucibus tortor porta augue ultrices semper. Proin dapibus scelerisque sapien, non fermentum erat. Aliquam dignissim non nisi interdum sodales. Cras ut enim sem. Maecenas convallis semper ex, non varius erat. Phasellus bibendum odio vitae dui tempus faucibus. Integer tincidunt, est id auctor tempor, lorem nisl molestie tortor, at interdum arcu mi imperdiet elit. Duis nec tortor a erat mattis fermentum.

Nam in aliquam neque. Curabitur leo nulla, blandit commodo leo id, tristique interdum erat. Cras at erat sed velit dapibus sollicitudin maximus sed tortor. Vivamus fermentum eros a purus efficitur, et eleifend felis fermentum. Nam efficitur mi erat, pulvinar tempor odio tempus vel. Suspendisse eget sagittis ante. Integer ultricies mi tortor. Quisque hendrerit massa scelerisque velit elementum, eget vehicula lacus maximus. Ut tortor leo, auctor eget viverra et, condimentum viverra nibh. Nulla in arcu porttitor, finibus eros vel, consequat augue. Praesent nec porttitor risus. Vivamus tristique, neque vitae feugiat vulputate, justo purus porta nisl, ut commodo dolor nisl ut mauris. Integer pellentesque efficitur laoreet. Quisque pulvinar ultrices quam, in sodales diam pretium eget.

Aenean mi arcu, condimentum et varius at, semper maximus turpis. Maecenas posuere consequat ultricies. Etiam eget lectus est. Praesent vulputate eu massa a ornare. Nam vestibulum, mauris a lacinia eleifend, leo nibh imperdiet ante, ut auctor ex massa id leo. Aenean ornare convallis lectus, nec pharetra mi tincidunt vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. In porttitor neque sed dui varius feugiat. Donec sem quam, lacinia volutpat est ac, aliquet egestas ante. Etiam blandit tempus ex ut ultricies. Aenean laoreet et tortor sed fringilla. Suspendisse potenti. Sed accumsan vitae mi id mattis. Vestibulum vitae mauris eget dui mattis iaculis nec vel est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Praesent interdum eget libero vel feugiat. Ut venenatis ultrices nibh, nec porttitor eros consectetur a. Cras eget lobortis nibh. Ut vitae mauris tempus, semper quam consectetur, iaculis lorem. Aliquam ultricies massa in aliquam auctor. Integer eget molestie ante. Ut ut lacus venenatis, hendrerit velit sed, consequat felis. Aenean et metus ac tortor fringilla tempus. Suspendisse potenti. In quis lobortis purus. Vivamus finibus lobortis sem eu facilisis. Quisque laoreet auctor eros, aliquam pulvinar enim. Curabitur non leo vitae felis gravida euismod non ac magna. Integer faucibus nisi id pellentesque consectetur. `},
        {id:15, likes:56, image:"https://images.unsplash.com/photo-1599598177777-21fece775e88?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=80", title:"How to style Raft", writer:"Unga Bunga", text: `

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pulvinar dignissim urna, id porttitor tortor eleifend non. Nullam eget viverra risus. Nulla sit amet lacus condimentum, sodales leo faucibus, semper est. Cras ultrices auctor purus eu tempus. Nullam id felis sodales, ultrices nunc a, consequat quam. Cras ac mi eget sem dapibus condimentum congue consectetur neque. Maecenas cursus euismod sodales. Phasellus id condimentum orci. In hac habitasse platea dictumst. Quisque vel posuere libero. Maecenas ac iaculis dolor, ut ultricies arcu. Maecenas convallis justo id quam tempor, vitae mollis purus auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Proin interdum, felis ut elementum cursus, ligula leo sodales diam, eu dapibus odio nulla sed nulla. Nunc diam felis, maximus nec nisl et, semper euismod risus. Suspendisse luctus, massa in interdum viverra, eros arcu vehicula nibh, quis vestibulum est ante suscipit nisi. Quisque sed elit non elit tempor volutpat id eu augue. Donec lacinia enim sed justo aliquet, quis rutrum felis aliquet. Pellentesque sit amet aliquam nisi. Integer in commodo turpis, quis sagittis diam. Nullam faucibus tortor porta augue ultrices semper. Proin dapibus scelerisque sapien, non fermentum erat. Aliquam dignissim non nisi interdum sodales. Cras ut enim sem. Maecenas convallis semper ex, non varius erat. Phasellus bibendum odio vitae dui tempus faucibus. Integer tincidunt, est id auctor tempor, lorem nisl molestie tortor, at interdum arcu mi imperdiet elit. Duis nec tortor a erat mattis fermentum.

Nam in aliquam neque. Curabitur leo nulla, blandit commodo leo id, tristique interdum erat. Cras at erat sed velit dapibus sollicitudin maximus sed tortor. Vivamus fermentum eros a purus efficitur, et eleifend felis fermentum. Nam efficitur mi erat, pulvinar tempor odio tempus vel. Suspendisse eget sagittis ante. Integer ultricies mi tortor. Quisque hendrerit massa scelerisque velit elementum, eget vehicula lacus maximus. Ut tortor leo, auctor eget viverra et, condimentum viverra nibh. Nulla in arcu porttitor, finibus eros vel, consequat augue. Praesent nec porttitor risus. Vivamus tristique, neque vitae feugiat vulputate, justo purus porta nisl, ut commodo dolor nisl ut mauris. Integer pellentesque efficitur laoreet. Quisque pulvinar ultrices quam, in sodales diam pretium eget.

Aenean mi arcu, condimentum et varius at, semper maximus turpis. Maecenas posuere consequat ultricies. Etiam eget lectus est. Praesent vulputate eu massa a ornare. Nam vestibulum, mauris a lacinia eleifend, leo nibh imperdiet ante, ut auctor ex massa id leo. Aenean ornare convallis lectus, nec pharetra mi tincidunt vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. In porttitor neque sed dui varius feugiat. Donec sem quam, lacinia volutpat est ac, aliquet egestas ante. Etiam blandit tempus ex ut ultricies. Aenean laoreet et tortor sed fringilla. Suspendisse potenti. Sed accumsan vitae mi id mattis. Vestibulum vitae mauris eget dui mattis iaculis nec vel est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Praesent interdum eget libero vel feugiat. Ut venenatis ultrices nibh, nec porttitor eros consectetur a. Cras eget lobortis nibh. Ut vitae mauris tempus, semper quam consectetur, iaculis lorem. Aliquam ultricies massa in aliquam auctor. Integer eget molestie ante. Ut ut lacus venenatis, hendrerit velit sed, consequat felis. Aenean et metus ac tortor fringilla tempus. Suspendisse potenti. In quis lobortis purus. Vivamus finibus lobortis sem eu facilisis. Quisque laoreet auctor eros, aliquam pulvinar enim. Curabitur non leo vitae felis gravida euismod non ac magna. Integer faucibus nisi id pellentesque consectetur. `},
      ];
      const [articles,setArticles] = useState(data);
    return (
        <View>
            
            <FlatList
                style={styles.list}
                contentContainerStyle={styles.listContainer}
                data = {articles}
                horizontal={false}
                keyExtractor= {(item)=>{
                    return item.id;
                }}
                renderItem= {({item}) =>{
                    return <TouchableOpacity
                    onPress={() => {
                        props.navigation.push('ArticleDetail',{article:item});
                   }}
                    >
                    <Image  
                        style={styles.image} 
                        source={{uri:item.image}}
                        PlaceholderContent= {<ActivityIndicator />}
                        >
                        <Text style={{fontSize:28,color:"white", margin: 10, marginLeft:10, fontFamily: "sans-serif-condensed", textAlign:"center"}} >{item.title}</Text>
                    </Image>
                    </TouchableOpacity> 
                }}
            />
        </View>
    )
}


const styles = StyleSheet.create({
    list: {
        marginTop: 10,
        marginHorizontal: 0,
        paddingHorizontal: 0,
        marginBottom: 10
    },
    listContainer:{
        alignItems:'center',
    },
    image: {
        marginHorizontal: 0,
        alignItems: "center",
        justifyContent: "center",
        aspectRatio: 2.2,
        width: '100%',
        height: 150 ,
        marginVertical: 10,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        borderRadius: 15,
    }
});

export default ArticleScreen;
